In [1]:
#import requireed packages
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as mpl

In [2]:
# read csv file 
df = pd.read_csv('Building_Permits.csv', low_memory=False)

In [3]:
#display first 5 rows in the dataset
df.head()

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992

In [39]:
df.shape

(198900, 43)

In [40]:
df.size

8552700

In [41]:
df.columns

Index(['Permit Number', 'Permit Type', 'Permit Type Definition',
       'Permit Creation Date', 'Block', 'Lot', 'Street Number',
       'Street Number Suffix', 'Street Name', 'Street Suffix', 'Unit',
       'Unit Suffix', 'Description', 'Current Status', 'Current Status Date',
       'Filed Date', 'Issued Date', 'Completed Date',
       'First Construction Document Date', 'Structural Notification',
       'Number of Existing Stories', 'Number of Proposed Stories',
       'Voluntary Soft-Story Retrofit', 'Fire Only Permit',
       'Permit Expiration Date', 'Estimated Cost', 'Revised Cost',
       'Existing Use', 'Existing Units', 'Proposed Use', 'Proposed Units',
       'Plansets', 'TIDF Compliance', 'Existing Construction Type',
       'Existing Construction Type Description', 'Proposed Construction Type',
       'Proposed Construction Type Description', 'Site Permit',
       'Supervisor District', 'Neighborhoods - Analysis Boundaries', 'Zipcode',
       'Location', 'Record ID'],
      dtype='object')

In [44]:
df.axes

[RangeIndex(start=0, stop=198900, step=1),
 Index(['Permit Number', 'Permit Type', 'Permit Type Definition',
        'Permit Creation Date', 'Block', 'Lot', 'Street Number',
        'Street Number Suffix', 'Street Name', 'Street Suffix', 'Unit',
        'Unit Suffix', 'Description', 'Current Status', 'Current Status Date',
        'Filed Date', 'Issued Date', 'Completed Date',
        'First Construction Document Date', 'Structural Notification',
        'Number of Existing Stories', 'Number of Proposed Stories',
        'Voluntary Soft-Story Retrofit', 'Fire Only Permit',
        'Permit Expiration Date', 'Estimated Cost', 'Revised Cost',
        'Existing Use', 'Existing Units', 'Proposed Use', 'Proposed Units',
        'Plansets', 'TIDF Compliance', 'Existing Construction Type',
        'Existing Construction Type Description', 'Proposed Construction Type',
        'Proposed Construction Type Description', 'Site Permit',
        'Supervisor District', 'Neighborhoods - Analysis Boundaries', 'Zipcode',
        'Location', 'Record ID'],
       dtype='object')]

In [19]:
#types of values in each column
df.dtypes

Permit Number                              object
Permit Type                                object
Permit Type Definition                     object
Permit Creation Date                       object
Block                                      object
Lot                                        object
Street Number                               int64
Street Number Suffix                       object
Street Name                                object
Street Suffix                              object
Unit                                      float64
Unit Suffix                                object
Description                                object
Current Status                             object
Current Status Date                        object
Filed Date                                 object
Issued Date                                object
Completed Date                             object
First Construction Document Date           object
Structural Notification                    object
Number of Existing Stories                float64
Number of Proposed Stories                float64
Voluntary Soft-Story Retrofit              object
Fire Only Permit                           object
Permit Expiration Date                     object
Estimated Cost                            float64
Revised Cost                              float64
Existing Use                               object
Existing Units                            float64
Proposed Use                               object
Proposed Units                            float64
Plansets                                  float64
TIDF Compliance                            object
Existing Construction Type                float64
Existing Construction Type Description     object
Proposed Construction Type                float64
Proposed Construction Type Description     object
Site Permit                                object
Supervisor District                       float64
Neighborhoods - Analysis Boundaries        object
Zipcode                                   float64
Location                                   object
Record ID                                   int64
dtype: object

In [6]:
#display values of columns and the count
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198900 entries, 0 to 198899
Data columns (total 43 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Permit Number                           198900 non-null  object
 1   Permit Type                             198900 non-null  int64
 2   Permit Type Definition                  198900 non-null  object
 3   Permit Creation Date                    198900 non-null  object
 4   Block                                   198900 non-null  object
 5   Lot                                     198900 non-null  object
 6   Street Number                           198900 non-null  int64
 7   Street Number Suffix                    2216 non-null    object
 8   Street Name                             198900 non-null  object
 9   Street Suffix                           196132 non-null  object
 10  Unit                                    29479 non-null   float64
 11  Unit Suffix                             1961 non-null    object
 12  Description                             198610 non-null  object
 13  Current Status                          198900 non-null  object
 14  Current Status Date                     198900 non-null  object
 15  Filed Date                              198900 non-null  object
 16  Issued Date                             183960 non-null  object
 17  Completed Date                          97191 non-null   object
 18  First Construction Document Date        183954 non-null  object
 19  Structural Notification                 6922 non-null    object
 20  Number of Existing Stories              156116 non-null  float64
 21  Number of Proposed Stories              156032 non-null  float64
 22  Voluntary Soft-Story Retrofit           35 non-null      object
 23  Fire Only Permit                        18827 non-null   object
 24  Permit Expiration Date                  147020 non-null  object
 25  Estimated Cost                          160834 non-null  float64
 26  Revised Cost                            192834 non-null  float64
 27  Existing Use                            157786 non-null  object
 28  Existing Units                          147362 non-null  float64
 29  Proposed Use                            156461 non-null  object
 30  Proposed Units                          147989 non-null  float64
 31  Plansets                                161591 non-null  float64
 32  TIDF Compliance                         2 non-null       object
 33  Existing Construction Type              155534 non-null  float64
 34  Existing Construction Type Description  155534 non-null  object
 35  Proposed Construction Type              155738 non-null  float64
 36  Proposed Construction Type Description  155738 non-null  object
 37  Site Permit                             5359 non-null    object
 38  Supervisor District                     197183 non-null  float64
 39  Neighborhoods - Analysis Boundaries     197175 non-null  object
 40  Zipcode                                 197184 non-null  float64
 41  Location                                197200 non-null  object
 42  Record ID                               198900 non-null  int64
dtypes: float64(12), int64(3), object(28)
memory usage: 65.3+ MB

In [22]:
#display total number of null values in each column
df.isnull().sum()

Permit Number                                  0
Permit Type                                    0
Permit Type Definition                         0
Permit Creation Date                           0
Block                                          0
Lot                                            0
Street Number                                  0
Street Number Suffix                      196684
Street Name                                    0
Street Suffix                               2768
Unit                                      169421
Unit Suffix                               196939
Description                                  290
Current Status                                 0
Current Status Date                            0
Filed Date                                     0
Issued Date                                14940
Completed Date                            101709
First Construction Document Date           14946
Structural Notification                   191978
Number of Existing Stories                 42784
Number of Proposed Stories                 42868
Voluntary Soft-Story Retrofit             198865
Fire Only Permit                          180073
Permit Expiration Date                     51880
Estimated Cost                             38066
Revised Cost                                6066
Existing Use                               41114
Existing Units                             51538
Proposed Use                               42439
Proposed Units                             50911
Plansets                                   37309
TIDF Compliance                           198898
Existing Construction Type                 43366
Existing Construction Type Description     43366
Proposed Construction Type                 43162
Proposed Construction Type Description     43162
Site Permit                               193541
Supervisor District                         1717
Neighborhoods - Analysis Boundaries         1725
Zipcode                                     1716
Location                                    1700
Record ID                                      0
dtype: int64

,Street Number,Unit,Number of Existing Stories,Number of Proposed Stories,Estimated Cost,Revised Cost,Existing Units,Proposed Units,Plansets,Existing Construction Type,Proposed Construction Type,Supervisor District,Zipcode,Record ID
count,198900.000000,29479.000000,156116.000000,156032.000000,1.608340e+05,1.928340e+05,147362.000000,147989.000000,161591.000000,155534.000000,155738.000000,197183.000000,197184.000000,1.989000e+05
mean,1121.728944,78.517182,5.705773,5.745043,1.689554e+05,1.328562e+05,15.666164,16.510950,1.274650,4.072878,4.089529,5.538403,94115.500558,1.162048e+12
std,1135.768948,326.981324,8.613455,8.613284,3.630386e+06,3.584903e+06,74.476321,75.220444,22.407345,1.585756,1.578766,2.887041,9.270131,4.918215e+11
min,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,94102.000000,1.293532e+10
25%,235.000000,0.000000,2.000000,2.000000,3.300000e+03,1.000000e+00,1.000000,1.000000,0.000000,3.000000,3.000000,3.000000,94109.000000,1.308567e+12
50%,710.000000,0.000000,3.000000,3.000000,1.100000e+04,7.000000e+03,1.000000,2.000000,2.000000,5.000000,5.000000,6.000000,94114.000000,1.371840e+12
75%,1700.000000,1.000000,4.000000,4.000000,3.500000e+04,2.870750e+04,4.000000,4.000000,2.000000,5.000000,5.000000,8.000000,94122.000000,1.435000e+12
max,8400.000000,6004.000000,78.000000,78.000000,5.379586e+08,7.805000e+08,1907.000000,1911.000000,9000.000000,5.000000,5.000000,11.000000,94158.000000,1.498342e+12

#### indentify the numeric and categorical variables in the dataset

In [58]:
#numeric variables
num_df = df.select_dtypes(include=['int64'])
num_df

        Street Number      Record ID
0                 140  1380611233945
1                 440  1420164406718
2                1647  1424856504716
3                1230  1443574295566
4                 950   144548169992
...               ...            ...
198895           1228  1489337276729
198896            580  1489462354993
198897           1568  1489539379952
198898            795  1489608233656
198899            838  1489796283803

[198900 rows x 2 columns]

In [60]:
num_df1 = num_df.columns.to_list()
num_df1

['Street Number', 'Record ID']

In [61]:
print(f"Numerical variables:\n {num_df1} \n")
print('--' * 15)

Numerical variables:
 ['Street Number', 'Record ID']

------------------------------

In [65]:
df[num_df1].describe()

       Street Number     Record ID
count  198900.000000  1.989000e+05
mean     1121.728944  1.162048e+12
std      1135.768948  4.918215e+11
min         0.000000  1.293532e+10
25%       235.000000  1.308567e+12
50%       710.000000  1.371840e+12
75%      1700.000000  1.435000e+12
max      8400.000000  1.498342e+12

In [57]:
#categorical variables
cat_df = df.select_dtypes(exclude=['int64'])
cat_df

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number Suffix,Street Name,Street Suffix,Unit,...,TIDF Compliance,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location
0,201505065519,4,sign - erect,05/06/2015,0326,023,NaN,Ellis,St,NaN,...,NaN,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)"
1,201604195146,4,sign - erect,04/19/2016,0306,007,NaN,Geary,St,0.0,...,NaN,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)"
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,NaN,Pacific,Av,NaN,...,NaN,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)"
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,NaN,Pacific,Av,0.0,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)"
4,201611283529,6,demolitions,11/28/2016,0342,001,NaN,Market,St,NaN,...,NaN,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198895,M862628,8,otc alterations permit,12/05/2017,0113,017A,NaN,Montgomery,St,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198896,201712055595,8,otc alterations permit,12/05/2017,0271,014,NaN,Bush,St,NaN,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN
198897,M863507,8,otc alterations permit,12/06/2017,4318,019,NaN,Indiana,St,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198898,M863747,8,otc alterations permit,12/06/2017,0298,029,NaN,Sutter,St,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198899,M864287,8,otc alterations permit,12/07/2017,0160,006,NaN,Pacific,Av,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
cat_df1 = cat_df.columns.to_list()
cat_df1

['Permit Number',
 'Permit Type',
 'Permit Type Definition',
 'Permit Creation Date',
 'Block',
 'Lot',
 'Street Number Suffix',
 'Street Name',
 'Street Suffix',
 'Unit',
 'Unit Suffix',
 'Description',
 'Current Status',
 'Current Status Date',
 'Filed Date',
 'Issued Date',
 'Completed Date',
 'First Construction Document Date',
 'Structural Notification',
 'Number of Existing Stories',
 'Number of Proposed Stories',
 'Voluntary Soft-Story Retrofit',
 'Fire Only Permit',
 'Permit Expiration Date',
 'Estimated Cost',
 'Revised Cost',
 'Existing Use',
 'Existing Units',
 'Proposed Use',
 'Proposed Units',
 'Plansets',
 'TIDF Compliance',
 'Existing Construction Type',
 'Existing Construction Type Description',
 'Proposed Construction Type',
 'Proposed Construction Type Description',
 'Site Permit',
 'Supervisor District',
 'Neighborhoods - Analysis Boundaries',
 'Zipcode',
 'Location']

In [64]:
# Frequency table of each categorical variable
for col in cat_df1:
    val = df[col].value_counts()
    print(f"\t{col}:")
    print(f"{val} \n")

	Permit Number:
201602179765    101
201602179758     66
201602179775     30
201409166451      9
201708165004      9
               ...
201605258413      1
201703292634      1
201409126163      1
201406300031      1
201301097563      1
Name: Permit Number, Length: 181495, dtype: int64

	Permit Type:
8    178844
3     14663
4      2892
2       950
6       600
7       511
1       349
5        91
Name: Permit Type, dtype: int64

	Permit Type Definition:
otc alterations permit                 178844
additions alterations or repairs        14663
sign - erect                             2892
new construction wood frame               950
demolitions                               600
wall or painted sign                      511
new construction                          349
grade or quarry or fill or excavate        91
Name: Permit Type Definition, dtype: int64

	Permit Creation Date:
09/15/2017    413
11/03/2015    396
02/17/2016    363
09/14/2017    335
06/27/2014    307
             ...
05/24/2016     55
12/26/2014     45
09/11/2012     17
03/28/2012      4
12/26/2012      1
Name: Permit Creation Date, Length: 1291, dtype: int64

	Block:
3708    1195
3735     750
7331     680
0289     640
3709     584
        ...
1077       1
4878       1
7046       1
0137       1
0469       1
Name: Block, Length: 4896, dtype: int64

	Lot:
001     10114
007      5317
002      5183
003      5042
006      4835
        ...
040I        1
049M        1
034H        1
034D        1
669         1
Name: Lot, Length: 1055, dtype: int64

	Street Number Suffix:
A    1501
B     291
V     228
C      56
E      28
F      24
G      12
H      11
K      11
D      11
R      10
L      10
J       9
I       7
P       3
N       2
0       1
Â½       1
Name: Street Number Suffix, dtype: int64

	Street Name:
Market            5443
California        4587
Mission           4209
Montgomery        2403
Geary             1966
                  ...
Augusta              1
Juan Bautista        1
Toyon                1
Chain Of Lakes       1
Hollywood            1
Name: Street Name, Length: 1704, dtype: int64

	Street Suffix:
St    138358
Av     43219
Bl      3555
Wy      3540
Dr      3267
Tr      1466
Ct       667
Pl       538
Rd       389
Ln       354
Hy       240
Pz       210
Pk       128
Cr        97
Al        83
Wk         9
Rw         5
Sw         2
So         2
No         2
Hl         1
Name: Street Suffix, dtype: int64

	Unit:
0.0       21410
1.0        1312
2.0         549
3.0         448
101.0       365
          ...
3401.0        1
2140.0        1
1112.0        1
448.0         1
2534.0        1
Name: Unit, Length: 660, dtype: int64

	Unit Suffix:
A             346
C             226
B             191
D             135
E              92
             ...
BLDG C          1
RESDL/REAR      1
#R-2            1
D4              1
PH1             1
Name: Unit Suffix, Length: 164, dtype: int64

	Description:
street space                                                                                                                                                                                                                           22163
reroofing                                                                                                                                                                                                                               9465
street space permit                                                                                                                                                                                                                     7549
re-roofing                                                                                                                                                                                                                              2351
streetspace                                                                                                                                                                                                                              819
                                                                                                                                                                                                                                       ...
2nd floor: remodel kitchen and bathroom, remove lathe and plaster and replace with new sheetrock, 5/8 type x. no structural work. electrical and plumbing under seperate permits.                                                          1
the project scope is the remodel of an extg 2 story building. total of 3 bedrooms and 2 1/2  baths.                                                                                                                                        1
remove (e) stucco on front (only) of building. repair damaged sheathing as needed. remove 3 (e) vinyl windows replace with marvin clad exterior (white) with wood interior. insulate as needed. restucco to match. paint as needed.        1
rear stair replace (3) stringers @ top level, repalce structural member & 2x6 boards (4) @ top deck, replace dry rot 2x6 boards @ top level & replace several 2x6 at steps & 2x4 @railing repair i n kind less than 50%                    1
1st & 2nd floor - install new fire alarm devices on the tenant area shell project. new elevator connecitons for recalls & shunt trip, 3-smoke detectors, 1 heat detector, 3 relays, 6 speaker/strobes. ref pa #2013.03.26.3069             1
Name: Description, Length: 134272, dtype: int64

	Current Status:
complete       97077
issued         83559
filed          12043
withdrawn       1754
cancelled       1536
expired         1370
approved         733
reinstated       563
suspend          193
revoked           50
plancheck         16
appeal             2
disapproved        2
incomplete         2
Name: Current Status, dtype: int64

	Current Status Date:
09/15/2017    474
09/14/2017    404
06/15/2016    370
02/22/2018    364
02/23/2018    363
             ...
11/02/2014      1
03/02/2019      1
12/25/2014      1
08/13/2016      1
03/27/2016      1
Name: Current Status Date, Length: 1307, dtype: int64

	Filed Date:
09/15/2017    412
11/03/2015    366
02/17/2016    364
09/14/2017    332
06/27/2014    305
             ...
12/24/2014     68
12/24/2015     65
07/03/2015     60
05/24/2016     56
12/26/2014     45
Name: Filed Date, Length: 1288, dtype: int64

	Issued Date:
06/15/2016    341
07/26/2016    274
12/18/2015    272
12/10/2015    234
11/07/2017    233
             ...
12/24/2014     64
05/24/2016     63
12/26/2014     55
12/31/2015     54
12/12/2015      2
Name: Issued Date, Length: 1289, dtype: int64

	Completed Date:
10/30/2015    206
01/02/2014    169
12/20/2017    162
11/26/2013    161
10/10/2017    160
             ...
03/23/2013      3
01/04/2013      2
12/25/2014      1
11/02/2014      1
01/07/2013      1
Name: Completed Date, Length: 1300, dtype: int64

	First Construction Document Date:
11/07/2016    339
11/01/2016    254
12/10/2015    236
11/07/2017    235
10/11/2017    233
             ...
07/03/2015     65
12/24/2014     62
12/31/2015     56
12/26/2014     53
05/24/2016     42
Name: First Construction Document Date, Length: 1288, dtype: int64

	Structural Notification:
Y    6922
Name: Structural Notification, dtype: int64

	Number of Existing Stories:
2.0     52767
3.0     45740
4.0     16055
1.0      8793
5.0      3767
        ...
49.0        3
62.0        2
2.5         2
1.5         1
78.0        1
Name: Number of Existing Stories, Length: 64, dtype: int64

	Number of Proposed Stories:
2.0     50991
3.0     46802
4.0     17593
1.0      7893
5.0      4044
        ...
49.0        3
47.0        3
2.5         2
78.0        1
1.5         1
Name: Number of Proposed Stories, Length: 64, dtype: int64

	Voluntary Soft-Story Retrofit:
Y    35
Name: Voluntary Soft-Story Retrofit, dtype: int64

	Fire Only Permit:
Y    18827
Name: Fire Only Permit, dtype: int64

	Permit Expiration Date:
02/28/2018    302
02/24/2018    239
05/31/2018    234
05/04/2018    228
06/21/2018    228
             ...
01/23/2023      1
11/22/2022      1
03/21/2021      1
12/10/2022      1
06/15/2021      1
Name: Permit Expiration Date, Length: 2232, dtype: int64

	Estimated Cost:
1.0         17014
10000.0      6695
5000.0       6437
20000.0      5702
15000.0      4779
            ...
76600.0         1
20119.0         1
40240.0         1
737000.0        1
56898.0         1
Name: Estimated Cost, Length: 11395, dtype: int64

	Revised Cost:
1.0         47228
0.0          8513
10000.0      5474
5000.0       5453
20000.0      4696
            ...
21175.0         1
25690.0         1
21173.0         1
677523.0        1
30416.0         1
Name: Revised Cost, Length: 12629, dtype: int64

	Existing Use:
1 family dwelling       46766
apartments              40798
office                  24616
2 family dwelling       20987
retail sales             6910
                        ...
bath house                  2
roofing materials           1
orphanage                   1
dairies/dairy equip.        1
child care                  1
Name: Existing Use, Length: 93, dtype: int64

	Existing Units:
1.0      47346
0.0      29134
2.0      21804
3.0       8616
6.0       6066
         ...
674.0        1
289.0        1
550.0        1
480.0        1
540.0        1
Name: Existing Units, Length: 348, dtype: int64

	Proposed Use:
1 family dwelling       46346
apartments              43032
office                  23962
2 family dwelling       22061
retail sales             5079
                        ...
meat/produce marts          2
not applicable              1
orphanage                   1
roofing materials           1
dairies/dairy equip.        1
Name: Proposed Use, Length: 94, dtype: int64

	Proposed Units:
1.0       46913
0.0       26884
2.0       22891
3.0        9347
6.0        5872
          ...
1000.0        1
1911.0        1
312.0         1
241.0         1
319.0         1
Name: Proposed Units, Length: 368, dtype: int64

	Plansets:
2.0       98088
0.0       63244
3.0         250
4.0           3
1.0           2
6.0           2
20.0          1
9000.0        1
Name: Plansets, dtype: int64

	TIDF Compliance:
Y    1
P    1
Name: TIDF Compliance, dtype: int64

	Existing Construction Type:
5.0    113350
1.0     28072
3.0      9663
2.0      4068
4.0       381
Name: Existing Construction Type, dtype: int64

	Existing Construction Type Description:
wood frame (5)    113350
constr type 1      28072
constr type 3       9663
constr type 2       4068
constr type 4        381
Name: Existing Construction Type Description, dtype: int64

	Proposed Construction Type:
5.0    114382
1.0     27841
3.0      9360
2.0      3778
4.0       377
Name: Proposed Construction Type, dtype: int64

	Proposed Construction Type Description:
wood frame (5)    114382
constr type 1      27841
constr type 3       9360
constr type 2       3778
constr type 4        377
Name: Proposed Construction Type Description, dtype: int64

	Site Permit:
Y    5359
Name: Site Permit, dtype: int64

	Supervisor District:
3.0     28649
8.0     26760
2.0     25483
6.0     24797
5.0     19045
9.0     16362
7.0     14365
1.0     13038
10.0    12152
4.0      9592
11.0     6940
Name: Supervisor District, dtype: int64

	Neighborhoods - Analysis Boundaries:
Financial District/South Beach    21816
Mission                           14681
Sunset/Parkside                   10207
West of Twin Peaks                 8739
Castro/Upper Market                8527
Pacific Heights                    8508
Marina                             8244
Outer Richmond                     7854
Noe Valley                         7844
South of Market                    7572
Bernal Heights                     6067
Nob Hill                           6009
Haight Ashbury                     5798
Inner Sunset                       5776
Bayview Hunters Point              5669
Russian Hill                       5495
Hayes Valley                       5489
Tenderloin                         4783
Inner Richmond                     4458
Potrero Hill                       4293
Presidio Heights                   4084
North Beach                        4054
Western Addition                   3867
Chinatown                          3765
Lone Mountain/USF                  3358
Excelsior                          3072
Oceanview/Merced/Ingleside         2654
Glen Park                          2637
Mission Bay                        2287
Outer Mission                      2242
Twin Peaks                         1702
Portola                            1433
Lakeshore                          1308
Seacliff                            992
Visitacion Valley                   900
Japantown                           700
Treasure Island                      81
Golden Gate Park                     64
Presidio                             51
Lincoln Park                         49
McLaren Park                         46
Name: Neighborhoods - Analysis Boundaries, dtype: int64

	Zipcode:
94110.0    17837
94114.0    13404
94117.0    11780
94109.0    11348
94103.0    10986
94115.0    10095
94118.0     9812
94123.0     9515
94122.0     8886
94105.0     8628
94112.0     7897
94121.0     7773
94107.0     7706
94131.0     7664
94133.0     7424
94102.0     7164
94116.0     6421
94111.0     5385
94108.0     5320
94124.0     5265
94127.0     4993
94104.0     4229
94132.0     3507
94134.0     2983
94158.0     1058
94130.0       81
94129.0       23
Name: Zipcode, dtype: int64

	Location:
(37.79226164705184, -122.4034859571375)      554
(37.79294896659241, -122.39809861435491)     330
(37.728556952954136, -122.47676641508518)    281
(37.77523036414975, -122.4174703200545)      276
(37.78977799888473, -122.40173648131338)     252
                                            ...
(37.780086582070936, -122.46818277931582)      1
(37.778371032133265, -122.50428885956147)      1
(37.76294954317267, -122.47745705971431)       1
(37.72261255193638, -122.40404180412017)       1
(37.77393825515132, -122.46947069008483)       1
Name: Location, Length: 57604, dtype: int64

In [ ]:
df[]

In [54]:
#show all unique calues of permit type
df['Permit Type'].unique()

array(['4', '3', '8', '6', '7', '1', '5', '2'], dtype=object)

In [ ]:
df.drop(['A'], axis=1)